name: resnet34
log_name: resnet34_voc12_0.1
log_dir: ./result
log_overwrite: False
use_tensorboard: True
distributed_multiprocessing: False
distributed_backend: nccl
dataset: voc12
dataset_root: ../../dataset/VOC/
seed: 42
labeled_ratio: 1.0
#train_list: ./data/voc12/train_aug.txt
train_ulb_list: ./data/voc12/train_aug.txt
eval_list: ./data/voc12/val.txt
verbose_interval: 3
train:
  input_size: 512
  crop_size: 480
  batch_size: 16
  epochs: 250
  loss: 
    name: AsymmetricLoss
    kwargs:
      gamma_neg: 4
      gamma_pos: 0
      clip: 0.05
      disable_torch_grad_focal_loss: True
eval:
  crop_size: 512
  batch_size: 32
  thres_start: 5
  thres_limit: 75
  thres_jump: 5
  cam_type: gradcam
  cam_thres: 15
optim:
  name: Adam
  kwargs:
    lr: 0.0001
    weight_decay: 0.0001
    # (N(dataset) // batch_size) * epochs
    #max_step: 16600
scheduler:
  name: OneCycleLR
  kwargs:
    max_lr: 0.0001
    # (N(dataset) // batch_size)
    steps_per_epoch: 165
    epochs: 250
    pct_start: 0.2