network: resnet50
log_name: resnet50_voc12_gradcam
log_dir: ./result
log_overwrite: True
use_tensorboard: True
distributed_multiprocessing: False
distributed_url: tcp://127.0.0.1:10010
distributed_backend: nccl
dataset: voc12
seed: 42
labeled_ratio: 1.0
train_list: ./data/voc12/train_aug.txt
train_ulb_list: False
eval_list: ./data/voc12/val.txt
verbose_interval: 3
train:
  input_size: 512
  crop_size: 480
  batch_size: 32
  epochs: 20
  loss: 
    name: MultiLabelSoftMarginLoss
    kwargs:
      reduction: none
eval:
  crop_size: 480
  batch_size: 64
  thres_start: 5
  thres_limit: 100
  thres_jump: 5
  cam_type: gradcam
  cam_thres: 15
  multi_scale:
    - 1.0
    - 0.5
    - 1.5
    - 2.0
optim:
  name: AdamW
  kwargs:
    lr: 0.0001
    weight_decay: 0.01
    # (N(dataset) // batch_size) * epochs
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 20    
    eta_min: 2e-6  