name: resnet
optim:
  name: PolyOptimizer
  kwargs:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005
    # (N(dataset) // batch_size) * epochs
    max_step: 22960
net:
  crop_size: 512
  batch_size: 16
  epochs: 35
