name: resnet152
log_name: resnet152_voc12_0.05
log_dir: ./result
log_overwrite: False
use_tensorboard: True
distributed_multiprocessing: False
distributed_backend: nccl
dataset: voc12
dataset_root: ../../dataset/VOC/
seed: 42
labeled_ratio: 1.0
#train_list: ./data/voc12/train_aug.txt
train_ulb_list: ./data/voc12/train_aug.txt
eval_list: ./data/voc12/val.txt
verbose_interval: 3
train:
  input_size: 512
  crop_size: 480
  batch_size: 32
  epochs: 150 #35
  loss: MultiLabelSoftMarginLoss
eval:
  crop_size: 512
  batch_size: 64
  thres_start: 5
  thres_limit: 100
  thres_jump: 5
  cam_type: gradcam
  cam_thres: 15
optim:
  name: PolyOptimizer
  kwargs:
    lr: 0.03 #0.1
    momentum: 0.9
    weight_decay: 0.0005
    # (N(dataset) // batch_size) * epochs
    max_step: 8300