name: vgg19
optim:
  name: SGD
  lr: 0.001
  kwargs:
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True
scheduler:
  name: MultiStepLR
  kwargs:
    # LR decay points (list)
    milestones:
      - 5
      - 10
    gamma: 0.1
net:
  crop_size: 512
  batch_size: 8
  epochs: 30