network: vgg19
log_name: vgg19_voc12_1.0
log_dir: ./result
log_overwrite: False
use_tensorboard: True
distributed_multiprocessing: False
distributed_backend: nccl
dataset: voc12
dataset_root: ../../dataset/VOC/
seed: 42
labeled_ratio: 1.0
train_list: ./data/voc12/train_aug.txt
train_ulb_list: False
eval_list: ./data/voc12/val.txt
verbose_interval: 3
train:
  input_size: 512
  crop_size: 480
  batch_size: 8
  epochs: 30
eval:
  crop_size: 480
  batch_size: 64
  thres_start: 5
  thres_limit: 100
  thres_jump: 5
  cam_type: gradcam
optim:
  name: SGD
  lr: 0.001
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0001
    nesterov: True
scheduler:
  name: MultiStepLR
  kwargs:
    milestones:
      - 10
      - 20
    gamma: 0.1