network: vgg16
log_name: vgg16_voc12_gradcam
log_dir: ./result
log_overwrite: False
use_tensorboard: True
distributed_multiprocessing: False
distributed_backend: nccl
dataset: voc12
seed: 42
labeled_ratio: 1.0
train_list: ./data/voc12/train_aug.txt
train_ulb_list: False
eval_list: ./data/voc12/train.txt
verbose_interval: 2
train:
  input_size: 512
  crop_size: 480
  batch_size: 16
  epochs: 20
  loss: 
    name: MultiLabelSoftMarginLoss
    kwargs:
      reduction: none
eval:
  crop_size: 480
  batch_size: 64
  thres_start: 10
  thres_limit: 80
  thres_jump: 5
  cam_type: gradcam
optim:
  name: AdamW
  kwargs:
    lr: 0.0001
    weight_decay: 0.01
    # (N(dataset) // batch_size) * epochs
scheduler:
  name: CosineAnnealingLR
  kwargs:
    T_max: 20    
    eta_min: 2e-6  